### ISSUE TITLE
Unknown provider: iProvider

### ISSUE THREAD

**Issue by Defcon0** [emeryg/ionic-notification-bar#1]
Hello,

I just installed your plugin into my ionic 1 installation. Unfortunately I get:

Error: [$injector:unpr] Unknown provider: iProvider <- i <- $notificationBar
http://errors.angularjs.org/1.5.3/$injector/unpr?p0=iProvider%20%3C-NaN%20%3C-%20%24notificationBar
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:13438:12
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:17788:19
    at Object.getService [as get] (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17941:39)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:17793:45
    at getService (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17941:39)
    at injectionArgs (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17965:58)
    at Object.instantiate (http://localhost:8100/lib/ionic/js/ionic.bundle.js:18007:18)
    at Object.<anonymous> (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17850:24)
    at Object.invoke (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17995:19)
    at Object.enforcedReturnValue [as $get] (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17834:37)

I did exactly the steps you suggested in the README.md. Is this a bug?

**Comment by emeryg** [comment]
Yes this is a bug, thanks for the observation.

There was a problem with the minified version (the angularjs $log provider was minified).
This is fixed.

Regards,
Guillaume

**Comment by Defcon0** [comment]
Awesome. Thanks for the quick fix :-)

**Comment by Defcon0** [comment]
Could you please add a new version (a tag) for your fix? I try to avoid adding branches (master) to my productive project. Thanks.

**Comment by Defcon0** [comment]
Thanks :-)
